version: '3'

services:
  backend:
    image: larsrickert/sample-node-api
    restart: always
    build: .
    expose:
      - '${API_PORT}'
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      API_PORT: '${API_PORT}'
    # comment in when deployed to rickstack VPS
    #   VIRTUAL_HOST: example.rickstack.de
    #   LETSENCRYPT_HOST: example.rickstack.de
    #   LETSENCRYPT_EMAIL: bonus_isotop_0a@icloud.com
# comment in when deployed to rickstack VPS
# networks:
#   default:
#     external:
#       name: nginx-proxy
