version: '3'

services:
  backend:
    image: larsrickert/sample-node-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - ./logs:/usr/src/app/logs
    # Needed when deploying on RickStack VPS
    # environment:
    #   VIRTUAL_HOST: '${DOCKER_DOMAIN}'
    #   LETSENCRYPT_HOST: '${DOCKER_DOMAIN}'
    #   LETSENCRYPT_EMAIL: '${DOCKER_LETSENCRYPT_EMAIL}'
# comment in when deployed to rickstack VPS
# networks:
#   default:
#     name: nginx-proxy
#     external: true
