version: '3'

services:
  app:
    build: .
    image: larsrickert/template-express
    restart: always
    # remove ports binding when deploying with nginx-proxy
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - ./logs:/usr/src/app/logs
    # Needed when deploying with nginx-proxy: https://github.com/larsrickert/nginx-proxy
    # environment:
    #   VIRTUAL_HOST: '${DOCKER_DOMAIN}'
    #   LETSENCRYPT_HOST: '${DOCKER_DOMAIN}'
# comment in when deployed with nginx-proxy
# networks:
#   default:
#     name: nginx-proxy
#     external: true
